steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/burner-amogaikw1/flash/$_SERVICE_NAME:$SHORT_SHA', '.']
  # Push the container image to Container Registry
  #  us-central1-docker.pkg.dev/burner-amogaikw1/flash/gcp-compliance-api:$SHORT_SHA
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/burner-amogaikw1/flash/$_SERVICE_NAME:$SHORT_SHA']
  # # Deploy container image to Cloud Run
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: gcloud
  #   args:
  #     - 'run'
  #     - 'deploy'
  #     - '$_SERVICE_NAME'
  #     - '--image'
  #     - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
  #     - '--region'
  #     - '$_DEPLOY_REGION'