services:
  compliance:
    build: ./
    container_name: complianceCompose
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase
    depends_on: [postgres]
  postgres:
    image: "postgres:latest"
    container_name: postgresCompose
    environment:
      - "POSTGRES_DB=mydatabase"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=myuser"
    ports:
      - 5432:5432
