apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-consumer
spec:
  selector:
    matchLabels:
      app: compliance-consumer
  template:
    metadata:
      labels:
        app: compliance-consumer
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-key
      - name: database-config
        configMap:
          name: app-database-config
      - name: database-authentication
        secret:
          secretName: app-database-auth
      containers:
      - name: compliance-consumer
        image: compliance-consumer:1
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"